import re

with open("script.js", "r") as f:
    content = f.read()

# Add imports at the very beginning of the file
imports = """import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import { getAuth, signInWithPopup, GoogleAuthProvider, onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";

"""
content = imports + content

# We need to replace the Google Identity Services section
# Find the start and end of the GSI section
start_marker = "  // ==========================================\n  // GOOGLE LOGIN INTEGRATION (GSI)"
end_marker = "  // ==========================================\n  // CONFETTI CELEBRATION EFFECT (Canvas)"

auth_section_start = content.find(start_marker)
auth_section_end = content.find(end_marker)

if auth_section_start != -1 and auth_section_end != -1:
    firebase_auth_code = """  // ==========================================
  // FIREBASE AUTHENTICATION (GOOGLE SIGN-IN)
  // ==========================================
  const loggedOutContainer = document.getElementById('rsvp-logged-out');
  const loggedInContainer = document.getElementById('rsvp-logged-in');
  const googleLoginBtnContainer = document.getElementById('google-login-btn');
  const googleLogoutBtn = document.getElementById('google-logout-btn');
  const userAvatar = document.getElementById('user-avatar');
  const userDisplayName = document.getElementById('user-display-name');
  const userEmailAddress = document.getElementById('user-email-address');
  const guestNameInput = document.getElementById('guest-name');
  const rsvpForm = document.getElementById('rsvp-form');

  // Login UI transition
  function loginUser(name, email, picture) {
    loggedInUser = { name, email, picture };

    // Save to local storage for quick access
    localStorage.setItem('wedding_auth_user', JSON.stringify(loggedInUser));

    // Update UI elements
    userAvatar.src = picture || "https://www.gstatic.com/images/branding/product/2x/avatar_square_blue_120dp.png";
    userDisplayName.innerText = name;
    userEmailAddress.innerText = email;
    guestNameInput.value = name;

    // Toggle containers
    loggedOutContainer.style.display = 'none';
    loggedInContainer.style.display = 'block';

    // If they already responded previously, show success state, but allow them to update
    const savedRsvp = localStorage.getItem('wedding_rsvp');
    if (savedRsvp) {
      const rsvpData = JSON.parse(savedRsvp);
      if (rsvpData.email.toLowerCase().trim() === email.toLowerCase().trim()) {
        showSuccessUI(rsvpData.name, rsvpData.status, true);
      }
    }
  }

  // Logout UI transition
  function logoutUser() {
    loggedInUser = null;
    localStorage.removeItem('wedding_auth_user');

    // Reset fields
    userAvatar.src = "";
    userDisplayName.innerText = "";
    userEmailAddress.innerText = "";
    guestNameInput.value = "";

    // Toggle containers back
    loggedInContainer.style.display = 'none';
    document.getElementById('rsvp-success').style.display = 'none';
    rsvpForm.style.display = 'block';
    loggedOutContainer.style.display = 'block';
  }

  // Initialize Firebase and Auth
  async function initializeFirebaseAuth() {
    try {
      // Fetch the automatic Firebase config generated by Firebase Hosting
      const response = await fetch('/__/firebase/init.json');
      const firebaseConfig = await response.json();
      
      const app = initializeApp(firebaseConfig);
      const auth = getAuth(app);
      const provider = new GoogleAuthProvider();

      // Listen for authentication state changes
      onAuthStateChanged(auth, (user) => {
        if (user) {
          loginUser(user.displayName, user.email, user.photoURL);
        } else {
          logoutUser();
        }
      });

      // Render custom Google Sign-In button
      googleLoginBtnContainer.innerHTML = `
        <button type="button" class="btn btn-primary" id="firebase-login-btn" style="background-color: #4285F4; border-radius: 4px; padding: 10px 20px; font-size: 0.95rem; font-weight: 500; display: inline-flex; align-items: center; gap: 10px; border: none; box-shadow: 0 2px 4px rgba(0,0,0,0.15);">
          <svg width="18" height="18" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
            <path d="M17.64 9.2c0-.637-.057-1.251-.164-1.84H9v3.481h4.844c-.209 1.125-.843 2.078-1.796 2.717v2.258h2.908c1.702-1.567 2.684-3.874 2.684-6.615z" fill="#4285F4"/>
            <path d="M9 18c2.43 0 4.467-.806 5.956-2.184l-2.908-2.258c-.806.54-1.837.86-3.048.86-2.344 0-4.328-1.584-5.036-3.711H.957v2.332C2.438 15.93 5.482 18 9 18z" fill="#34A853"/>
            <path d="M3.964 10.707c-.18-.54-.282-1.117-.282-1.707s.102-1.167.282-1.707V4.96H.957C.347 6.173 0 7.547 0 9s.347 2.827.957 4.04l3.007-2.333z" fill="#FBBC05"/>
            <path d="M9 3.58c1.32 0 2.508.454 3.44 1.346l2.582-2.58C13.463.89 11.426 0 9 0 5.482 0 2.438 2.07 1.057 5.097L3.964 7.43c.708-2.127 2.692-3.71 5.036-3.71z" fill="#EA4335"/>
          </svg>
          Sign in with Google
        </button>
      `;

      document.getElementById('firebase-login-btn').addEventListener('click', () => {
        signInWithPopup(auth, provider).catch((error) => {
          console.error("Google Sign-In Error:", error);
          alert("Sign-in failed. Please try again.");
        });
      });

      googleLogoutBtn.addEventListener('click', () => {
        signOut(auth).catch((error) => {
          console.error("Sign-out Error:", error);
        });
      });

    } catch (error) {
      console.error("Firebase initialization failed. Are you testing locally without Firebase emulator? ", error);
      googleLoginBtnContainer.innerHTML = `<div style="color:red; font-size: 0.9rem;">Unable to load Firebase Auth. Please ensure this site is accessed via Firebase Hosting.</div>`;
    }
  }

  initializeFirebaseAuth();

"""
    new_content = content[:auth_section_start] + firebase_auth_code + content[auth_section_end:]
    
    with open("script.js", "w") as f:
        f.write(new_content)
    print("Successfully updated script.js")
else:
    print("Could not find the section to replace")
